[project]
name = 'Geoengineering-Proposal-and-Impact-Assessment'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.climate-data]
path = 'contracts/climate-data.clar'
clarity_version = 2
epoch = 2.5

[contracts.geo-token]
path = 'contracts/geo-token.clar'
clarity_version = 2
epoch = 2.5

[contracts.impact-assessment_]
path = 'contracts/impact-assessment_.clar'
clarity_version = 2
epoch = 2.5

[contracts.proposal-review]
path = 'contracts/proposal-review.clar'
clarity_version = 2
epoch = 2.5

[contracts.voting]
path = 'contracts/voting.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
